// Writes supabase/seed.sql from src/lib/fixtures.ts so the local database and the
// no-database fallback show the same demo calendar.
// Run: pnpm db:seed-file (node --experimental-strip-types)

import { writeFileSync } from 'node:fs';
import { events, organizations, overrides, venues } from '../src/lib/fixtures.ts';

// Fixture ids are readable slugs; the tables use uuids. md5(text)::uuid is stable.
const id = (value: string) => `md5(${text(value)})::uuid`;

function text(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function textArray(values: readonly string[]): string {
  return `array[${values.map(text).join(', ')}]::text[]`;
}

const lines: string[] = [
  '-- Generated by scripts/generate-seed.ts from src/lib/fixtures.ts. Do not edit by hand.',
  ''
];

for (const org of organizations) {
  lines.push(
    `insert into organizations (id, name, slug, email, phone, website, social_links) values (${id(org.id)}, ${text(org.name)}, ${text(org.slug)}, ${text(org.email)}, ${text(org.phone)}, ${text(org.website)}, ${textArray(org.socialLinks ?? [])});`
  );
}
lines.push('');

for (const venue of venues) {
  lines.push(
    `insert into venues (id, org_id, name, address, lat, lng, city, country) values (${id(venue.id)}, ${id(venue.orgId)}, ${text(venue.name)}, ${text(venue.address)}, ${venue.lat}, ${venue.lng}, ${text(venue.city)}, ${text(venue.country)});`
  );
}
lines.push('');

for (const event of events) {
  lines.push(
    `insert into events (id, org_id, venue_id, categories, tags, status, rrule, dtstart_local, timezone, duration_minutes, price_kind, price_amount, source_lang) values (${id(event.id)}, ${id(event.orgId)}, ${id(event.venueId)}, ${textArray(event.categories)}, ${textArray(event.tags)}, ${text(event.status)}, ${text(event.rrule)}, ${text(event.dtstartLocal)}, ${text(event.timezone)}, ${event.durationMinutes}, ${text(event.price.kind)}, ${event.price.amount ?? 'null'}, ${text(event.sourceLang)});`
  );
  for (const locale of ['de', 'en', 'fr'] as const) {
    lines.push(
      `insert into event_i18n (event_id, locale, title, description, note) values (${id(event.id)}, '${locale}', ${text(event.title[locale])}, ${text(event.description[locale])}, ${text(event.note?.[locale] ?? '')});`
    );
  }
}
lines.push('');

for (const override of overrides) {
  lines.push(
    `insert into occurrence_overrides (event_id, occ_date, status, override_start_local) values (${id(override.eventId)}, ${text(override.date)}, ${text(override.status)}, ${text(override.overrideStartLocal)});`
  );
}

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n') + '\n');
